apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXlNakl4TVRZd01Gb1hEVE16TURReE9USXhNVFl3TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWJaCk5ueTFQaGVOMG13QklxSXc3VVg0WFNaMWozQ1N5aVlXcmlkNTlRdk9pRXJvYkFBYnYrS2lCcjJoM3JMVStUbHcKdDZEdWs5dS8ybG1sTjZxM0tDKzNldUlSWmVpNmRWUlE5UFdpVHorS010WmNsUHlSNVRZWWpHNU4vbkZhZCtPUwpZcjh1WGVCMWxpbW1aR2RDZkxXcE9xbE92UHpEZ2FGZ3IyWTIyaUFtdFdIcHVyc2RNYzdJS0lMZDR5b3lDL2hpCkhWenlFUzhocU43c1dzS1hxOW1odmt0Vi85Uk1rMC8waGJ3VmM2MTQ3WUdMTXF2YnhRNHM1NkNHT0dpWE9wVGUKUE1wb0RNQ0ErYjA4a2JxdURGR21rd0VPTkJ3blJsUktKcGw2cllxV3VteDVVYkszdFNITDIwSzRidGMyckdNegprb0pZYUM4R08zY1ExZ1YrWGJzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFSGpzZnZPR0NJZDdjdjlpWUNRN1lwZlN2RU9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRk9UQlFqMnQ1dUFkY08ySWRTcwp0bXFBaGhaVzZHZTZmQnNlL0MvUjgvUVlyVlY3WHM3VHdqKzJXLy9xc0tJQUZCVFFYT1Q1T2RkT3BCWmFRRFdPCitydmJpVE94bGYzbW5hNEZWaUw0VXVrUGxxSjVZcHd3a1Vna0dHaHZqMUoyeHo4U0MyZkNuMVlkRDU0TTJFTmsKdTBBVGFQdTJsdmx5VTVOTEQweHlGMEk5Y0E1c3M5V1RBSURBSElzdEZjYW9YaE9CUzlPalV2Qm5ueEkvQnd4dApiUURwWlRVYjRTaFowdHFYcC9YelZUenFleEc0WXlhQk16TDFNVGhUOHZ3eWJBV0Z2ZE1jMTlEQjd4bkJnUWNMCi80N1IvMVd5OUVxTklRTEJNWkNJS1BIWkZ5Ui9HNWQ4WVhqdjdEWklBNlNyK29LQ2VCcjQraEM3YmxJQ2RsUHkKbWN3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://0A7BC8AF1E57836EEB120B3F7055D155.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:523057940930:cluster/todo-app
- cluster:
    certificate-authority: /Users/vignaychanda/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 23 Apr 2023 17:03:24 EDT
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://127.0.0.1:62165
  name: minikube
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:523057940930:cluster/todo-app
    user: arn:aws:eks:us-east-2:523057940930:cluster/todo-app
  name: arn:aws:eks:us-east-2:523057940930:cluster/todo-app
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 23 Apr 2023 17:03:24 EDT
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:523057940930:cluster/todo-app
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - todo-app
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: minikube
  user:
    client-certificate: /Users/vignaychanda/.minikube/profiles/minikube/client.crt
    client-key: /Users/vignaychanda/.minikube/profiles/minikube/client.key
