# Part 1-5
# -------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
  selector:
    app: mongo


# Part 6
# -------------------------------------------
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongo
# spec:
#   replicas: 1
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 0
#   selector:
#     matchLabels:
#       app: mongo
#   template:
#     metadata:
#       labels:
#         app: mongo
#     spec:
#       containers:
#       - name: mongo
#         image: mongo
#         ports:
#         - containerPort: 27017
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
# spec:
#   ports:
#   - port: 27017
#   selector:
#     app: mongo